version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    groups:
      actions-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    groups:
      bun-dependencies:
        patterns:
          - "*"
